# Generated by Django 5.0.4 on 2024-05-05 09:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anno_title', models.CharField(max_length=200)),
                ('anno_description', models.CharField(max_length=200)),
                ('anno_image', models.ImageField(upload_to='anno/%Y/%m/%d/')),
                ('anno_date', models.DateField(auto_now_add=True)),
                ('anno_content', models.TextField()),
                ('anno_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
                'db_table': 'anno',
                'ordering': ['anno_date'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=200)),
                ('news_description', models.CharField(max_length=200)),
                ('news_image', models.ImageField(upload_to='news/%Y/%m/%d/')),
                ('news_content', models.TextField()),
                ('news_date', models.DateField(auto_now_add=True)),
                ('news_views', models.IntegerField(default=0)),
                ('news_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
                'db_table': 'news',
                'ordering': ['news_date'],
            },
        ),
    ]
