# Generated by Django 5.0.4 on 2024-05-10 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Regulations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_number', models.IntegerField()),
                ('reg_date', models.DateField(auto_now_add=True)),
                ('reg_sign', models.CharField(max_length=50)),
                ('reg_title', models.CharField(max_length=50)),
                ('reg_file', models.FileField(upload_to='regulations/')),
            ],
            options={
                'verbose_name': 'Regulation',
                'verbose_name_plural': 'Regulations',
                'db_table': 'regulations',
                'ordering': ['reg_number'],
            },
        ),
    ]
