# Generated by Django 5.0.4 on 2024-05-10 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Standards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_title', models.CharField(max_length=100)),
                ('standard_number', models.CharField(max_length=100)),
                ('standard_date', models.IntegerField()),
                ('standard_name', models.CharField(max_length=100)),
                ('standard_file', models.FileField(upload_to='standards/')),
            ],
            options={
                'verbose_name': 'Standard',
                'verbose_name_plural': 'Standards',
                'db_table': 'standards',
            },
        ),
    ]
